# Database configuration for development
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spotlight
    username: root
    password: root
  servlet:
    multipart:
      maxFileSize: 10GB
      maxRequestSize: 100GB
      location: ./img/

# Development server port
server:
  port: 8080
